language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.6.9 DJANGO_SETTINGS_MODULE="django_common.test_settings"
  - DJANGO=1.7.4 DJANGO_SETTINGS_MODULE="django_common.test_settings"
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7.4
    - python: "3.4"
      env: DJANGO=1.6.9
install:
  - pip install -q Django==$DJANGO --use-mirrors
script:
  - python setup.py test